### ISSUE TITLE
Add topics to repo Settings

### ISSUE THREAD

**Issue by MichaelCurrin** [tcbutler320/jek#21]
Add some topics like `#jekyll` or `#jekyll-theme` or `#netlify-site` and your repo can be found more easily via GitHub and Google

<img width="304" alt="Screen Shot 2021-06-18 at 4 12 01 pm" src="https://user-images.githubusercontent.com/18750745/122574487-fb2dab00-d04f-11eb-8fc5-891c88a67409.png">

**Comment by tcbutler320** [comment]
Done, thanks for the suggestion!!

<img width="349" alt="Screen Shot 2021-06-18 at 9 49 49 PM" src="https://user-images.githubusercontent.com/41709108/122627684-2085dd80-d07f-11eb-9a5a-b598c7e3a76c.png">
